# Data Understanding

In [1]:
# import all necessary references
import pandas as pd
import importlib.metadata
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import yaml

print(

    f"""
Pandas version: {pd.__version__}
Matplotlib Pyplot version: {importlib.metadata.version("matplotlib")}
Seaborn version: {sns.__version__}
PyYAML version: {yaml.__version__}    
    """
)

Pandas version: 2.0.0
Matplotlib Pyplot version: 3.7.1
Seaborn version: 0.12.2
PyYAML version: 6.0

In [2]:
pd.set_option("display.max_rows", 150)
pd.set_option("display.max_columns", 150)
pd.set_option("display.max_colwidth", None)
%matplotlib widget

## 1. Preparar o acesso aos dados

Local de armazenagem de dados brutos: `data/01_raw`

In [3]:
# Criar as referÃªncias para os arquivos
from pathlib import PurePath

raw_application_test_file_path = "../../data/01_raw/application_test.csv"
raw_application_train_file_path = "../../data/01_raw/application_train.csv"
raw_bureau_file_path = "../../data/01_raw/bureau.csv"
raw_bureau_balance_file_path = "../../data/01_raw/bureau_balance.csv"
raw_bureau_credit_card_balance_file_path = "../../data/01_raw/credit_card_balance.csv"
raw_installments_payments_file_path = "../../data/01_raw/credit_card_balance.csv"
raw_pos_cash_balance_file_path = "../../data/01_raw/POS_CASH_balance.csv"
raw_previous_application_file_path = "../../data/01_raw/previous_application.csv"
raw_sample_submission_file_path = "../../data/01_raw/sample_submission.csv"
home_credit_columns_description_file_path = "../../data/01_raw/HomeCredit_columns_description.csv"


raw_application_test_file = PurePath(raw_application_test_file_path)
raw_application_train_file = PurePath(raw_application_train_file_path)
raw_bureau_file = PurePath(raw_bureau_file_path)
raw_bureau_balance_file = PurePath(raw_bureau_balance_file_path)
raw_bureau_credit_card_balance_file = PurePath(raw_bureau_credit_card_balance_file_path)
raw_installments_payments_file = PurePath(raw_installments_payments_file_path)
raw_pos_cash_balance_file = PurePath(raw_pos_cash_balance_file_path)
raw_previous_application_file = PurePath(raw_previous_application_file_path)
raw_sample_submission_file = PurePath(raw_sample_submission_file_path)
home_credit_columns_description_file = PurePath(home_credit_columns_description_file_path)

In [4]:
home_credit_descriptors_df = pd.read_csv(
    filepath_or_buffer=home_credit_columns_description_file,
    engine="pyarrow",
    # dtype_backend="pyarrow",
    encoding='unicode_escape'
)
raw_application_train_df = pd.read_csv(
    filepath_or_buffer=raw_application_train_file,
    index_col="SK_ID_CURR",
    parse_dates=True,
    engine="pyarrow",
    # dtype_backend="pyarrow",
    encoding='unicode_escape'
)
raw_application_test_df = pd.read_csv(
    filepath_or_buffer=raw_application_test_file,
    index_col="SK_ID_CURR",
    parse_dates=True,
    engine="pyarrow",
    # dtype_backend="pyarrow",
    encoding='unicode_escape'
)

## 2. Entender tipos e significados dos dados

In [5]:
home_credit_descriptors_df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0                219 non-null    int64
 1   Table        219 non-null    object
 2   Row          219 non-null    object
 3   Description  219 non-null    object
 4   Special      219 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.7+ KB

In [6]:
# segregar os descritores apenas da tabela de trabalho atual
application_descriptors = home_credit_descriptors_df[home_credit_descriptors_df["Table"]=="application_{train|test}.csv"]
# application_descriptors.style.set_properties(
#     **{
#     'overflow-wrap': 'break-word',
#     },
#     subset='Description'
# )
application_descriptors.head(125)

,,Table,Row,Description,Special
0,1,application_{train|test}.csv,SK_ID_CURR,ID of loan in our sample,
1,2,application_{train|test}.csv,TARGET,"Target variable (1 - client with payment difficulties: he/she had late payment more than X days on at least one of the first Y installments of the loan in our sample, 0 - all other cases)",
2,5,application_{train|test}.csv,NAME_CONTRACT_TYPE,Identification if loan is cash or revolving,
3,6,application_{train|test}.csv,CODE_GENDER,Gender of the client,
4,7,application_{train|test}.csv,FLAG_OWN_CAR,Flag if the client owns a car,
5,8,application_{train|test}.csv,FLAG_OWN_REALTY,Flag if client owns a house or flat,
6,9,application_{train|test}.csv,CNT_CHILDREN,Number of children the client has,
7,10,application_{train|test}.csv,AMT_INCOME_TOTAL,Income of the client,
8,11,application_{train|test}.csv,AMT_CREDIT,Credit amount of the loan,
9,12,application_{train|test}.csv,AMT_ANNUITY,Loan annuity,
10,13,application_{train|test}.csv,AMT_GOODS_PRICE,For consumer loans it is the price of the goods for which the loan is given,
11,14,application_{train|test}.csv,NAME_TYPE_SUITE,Who was accompanying client when he was applying for the loan,
12,15,application_{train|test}.csv,NAME_INCOME_TYPE,"Clients income type (businessman, working, maternity leave,Â )",
13,16,application_{train|test}.csv,NAME_EDUCATION_TYPE,Level of highest education the client achieved,
14,17,application_{train|test}.csv,NAME_FAMILY_STATUS,Family status of the client,
15,18,application_{train|test}.csv,NAME_HOUSING_TYPE,"What is the housing situation of the client (renting, living with parents, ...)",
16,19,application_{train|test}.csv,REGION_POPULATION_RELATIVE,Normalized population of region where client lives (higher number means the client lives in more populated region),normalized
17,20,application_{train|test}.csv,DAYS_BIRTH,Client's age in days at the time of application,time only relative to the application
18,21,application_{train|test}.csv,DAYS_EMPLOYED,How many days before the application the person started current employment,time only relative to the application
19,22,application_{train|test}.csv,DAYS_REGISTRATION,How many days before the application did client change his registration,time only relative to the application
20,23,application_{train|test}.csv,DAYS_ID_PUBLISH,How many days before the application did client change the identity document with which he applied for the loan,time only relative to the application
21,24,application_{train|test}.csv,OWN_CAR_AGE,Age of client's car,
22,25,application_{train|test}.csv,FLAG_MOBIL,"Did client provide mobile phone (1=YES, 0=NO)",
23,26,application_{train|test}.csv,FLAG_EMP_PHONE,"Did client provide work phone (1=YES, 0=NO)",
24,27,application_{train|test}.csv,FLAG_WORK_PHONE,"Did client provide home phone (1=YES, 0=NO)",
25,28,application_{train|test}.csv,FLAG_CONT_MOBILE,"Was mobile phone reachable (1=YES, 0=NO)",
26,29,application_{train|test}.csv,FLAG_PHONE,"Did client provide home phone (1=YES, 0=NO)",
27,30,application_{train|test}.csv,FLAG_EMAIL,"Did client provide email (1=YES, 0=NO)",
28,31,application_{train|test}.csv,OCCUPATION_TYPE,What kind of occupation does the client have,
29,32,application_{train|test}.csv,CNT_FAM_MEMBERS,How many family members does client have,
30,33,application_{train|test}.csv,REGION_RATING_CLIENT,"Our rating of the region where client lives (1,2,3)",
31,34,application_{train|test}.csv,REGION_RATING_CLIENT_W_CITY,"Our rating of the region where client lives with taking city into account (1,2,3)",
32,35,application_{train|test}.csv,WEEKDAY_APPR_PROCESS_START,On which day of the week did the client apply for the loan,
33,36,application_{train|test}.csv,HOUR_APPR_PROCESS_START,Approximately at what hour did the client apply for the loan,rounded
34,37,application_{train|test}.csv,REG_REGION_NOT_LIVE_REGION,"Flag if client's permanent address does not match contact address (1=different, 0=same, at region level)",
35,38,application_{train|test}.csv,REG_REGION_NOT_WORK_REGION,"Flag if client's permanent address does not match work address (1=different, 0=same, at region level)",
36,39,application_{train|test}.csv,LIVE_REGION_NOT_WORK_REGION,"Flag if client's contact address does not match work address (1=different, 0=same, at region level)",
37,40,application_{train|test}.csv,REG_CITY_NOT_LIVE_CITY,"Flag if client's permanent address does not match contact address (1=different, 0=same, at city level)",
38,41,application_{train|test}.csv,REG_CITY_NOT_WORK_CITY,"Flag if client's permanent address does not match work address (1=different, 0=same, at city level)",
39,42,application_{train|test}.csv,LIVE_CITY_NOT_WORK_CITY,"Flag if client's contact address does not match work address (1=different, 0=same, at city level)",
40,43,application_{train|test}.csv,ORGANIZATION_TYPE,Type of organization where client works,
41,44,application_{train|test}.csv,EXT_SOURCE_1,Normalized score from external data source,normalized
42,45,application_{train|test}.csv,EXT_SOURCE_2,Normalized score from external data source,normalized
43,46,application_{train|test}.csv,EXT_SOURCE_3,Normalized score from external data source,normalized
44,47,application_{train|test}.csv,APARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
45,48,application_{train|test}.csv,BASEMENTAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
46,49,application_{train|test}.csv,YEARS_BEGINEXPLUATATION_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
47,50,application_{train|test}.csv,YEARS_BUILD_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
48,51,application_{train|test}.csv,COMMONAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
49,52,application_{train|test}.csv,ELEVATORS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
50,53,application_{train|test}.csv,ENTRANCES_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
51,54,application_{train|test}.csv,FLOORSMAX_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
52,55,application_{train|test}.csv,FLOORSMIN_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
53,56,application_{train|test}.csv,LANDAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
54,57,application_{train|test}.csv,LIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
55,58,application_{train|test}.csv,LIVINGAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
56,59,application_{train|test}.csv,NONLIVINGAPARTMENTS_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
57,60,application_{train|test}.csv,NONLIVINGAREA_AVG,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
58,61,application_{train|test}.csv,APARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
59,62,application_{train|test}.csv,BASEMENTAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
60,63,application_{train|test}.csv,YEARS_BEGINEXPLUATATION_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
61,64,application_{train|test}.csv,YEARS_BUILD_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
62,65,application_{train|test}.csv,COMMONAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
63,66,application_{train|test}.csv,ELEVATORS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
64,67,application_{train|test}.csv,ENTRANCES_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
65,68,application_{train|test}.csv,FLOORSMAX_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
66,69,application_{train|test}.csv,FLOORSMIN_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
67,70,application_{train|test}.csv,LANDAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
68,71,application_{train|test}.csv,LIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
69,72,application_{train|test}.csv,LIVINGAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
70,73,application_{train|test}.csv,NONLIVINGAPARTMENTS_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
71,74,application_{train|test}.csv,NONLIVINGAREA_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
72,75,application_{train|test}.csv,APARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
73,76,application_{train|test}.csv,BASEMENTAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
74,77,application_{train|test}.csv,YEARS_BEGINEXPLUATATION_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
75,78,application_{train|test}.csv,YEARS_BUILD_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
76,79,application_{train|test}.csv,COMMONAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
77,80,application_{train|test}.csv,ELEVATORS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
78,81,application_{train|test}.csv,ENTRANCES_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
79,82,application_{train|test}.csv,FLOORSMAX_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
80,83,application_{train|test}.csv,FLOORSMIN_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
81,84,application_{train|test}.csv,LANDAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
82,85,application_{train|test}.csv,LIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
83,86,application_{train|test}.csv,LIVINGAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
84,87,application_{train|test}.csv,NONLIVINGAPARTMENTS_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
85,88,application_{train|test}.csv,NONLIVINGAREA_MEDI,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized
86,89,application_{train|test}.csv,FONDKAPREMONT_MODE,"Normalized information about building where the client lives, What is average (_AVG suffix), modus (_MODE suffix), median (_MEDI suffix) apartment size, common area, living area, age of building, number of elevators, number of entrances, state of the building, number of floor",normalized

In [7]:
raw_application_train_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 307511 entries, 100002 to 456255
Data columns (total 121 columns):
 #    Column                        Non-Null Count   Dtype
---   ------                        --------------   -----
 0    TARGET                        307511 non-null  int64
 1    NAME_CONTRACT_TYPE            307511 non-null  object
 2    CODE_GENDER                   307511 non-null  object
 3    FLAG_OWN_CAR                  307511 non-null  object
 4    FLAG_OWN_REALTY               307511 non-null  object
 5    CNT_CHILDREN                  307511 non-null  int64
 6    AMT_INCOME_TOTAL              307511 non-null  float64
 7    AMT_CREDIT                    307511 non-null  float64
 8    AMT_ANNUITY                   307499 non-null  float64
 9    AMT_GOODS_PRICE               307233 non-null  float64
 10   NAME_TYPE_SUITE               307511 non-null  object
 11   NAME_INCOME_TYPE              307511 non-null  object
 12   NAME_EDUCATION_TYPE           307511 non-null  object
 13   NAME_FAMILY_STATUS            307511 non-null  object
 14   NAME_HOUSING_TYPE             307511 non-null  object
 15   REGION_POPULATION_RELATIVE    307511 non-null  float64
 16   DAYS_BIRTH                    307511 non-null  int64
 17   DAYS_EMPLOYED                 307511 non-null  int64
 18   DAYS_REGISTRATION             307511 non-null  float64
 19   DAYS_ID_PUBLISH               307511 non-null  int64
 20   OWN_CAR_AGE                   104582 non-null  float64
 21   FLAG_MOBIL                    307511 non-null  int64
 22   FLAG_EMP_PHONE                307511 non-null  int64
 23   FLAG_WORK_PHONE               307511 non-null  int64
 24   FLAG_CONT_MOBILE              307511 non-null  int64
 25   FLAG_PHONE                    307511 non-null  int64
 26   FLAG_EMAIL                    307511 non-null  int64
 27   OCCUPATION_TYPE               307511 non-null  object
 28   CNT_FAM_MEMBERS               307509 non-null  float64
 29   REGION_RATING_CLIENT          307511 non-null  int64
 30   REGION_RATING_CLIENT_W_CITY   307511 non-null  int64
 31   WEEKDAY_APPR_PROCESS_START    307511 non-null  object
 32   HOUR_APPR_PROCESS_START       307511 non-null  int64
 33   REG_REGION_NOT_LIVE_REGION    307511 non-null  int64
 34   REG_REGION_NOT_WORK_REGION    307511 non-null  int64
 35   LIVE_REGION_NOT_WORK_REGION   307511 non-null  int64
 36   REG_CITY_NOT_LIVE_CITY        307511 non-null  int64
 37   REG_CITY_NOT_WORK_CITY        307511 non-null  int64
 38   LIVE_CITY_NOT_WORK_CITY       307511 non-null  int64
 39   ORGANIZATION_TYPE             307511 non-null  object
 40   EXT_SOURCE_1                  134133 non-null  float64
 41   EXT_SOURCE_2                  306851 non-null  float64
 42   EXT_SOURCE_3                  246546 non-null  float64
 43   APARTMENTS_AVG                151450 non-null  float64
 44   BASEMENTAREA_AVG              127568 non-null  float64
 45   YEARS_BEGINEXPLUATATION_AVG   157504 non-null  float64
 46   YEARS_BUILD_AVG               103023 non-null  float64
 47   COMMONAREA_AVG                92646 non-null   float64
 48   ELEVATORS_AVG                 143620 non-null  float64
 49   ENTRANCES_AVG                 152683 non-null  float64
 50   FLOORSMAX_AVG                 154491 non-null  float64
 51   FLOORSMIN_AVG                 98869 non-null   float64
 52   LANDAREA_AVG                  124921 non-null  float64
 53   LIVINGAPARTMENTS_AVG          97312 non-null   float64
 54   LIVINGAREA_AVG                153161 non-null  float64
 55   NONLIVINGAPARTMENTS_AVG       93997 non-null   float64
 56   NONLIVINGAREA_AVG             137829 non-null  float64
 57   APARTMENTS_MODE               151450 non-null  float64
 58   BASEMENTAREA_MODE             127568 non-null  float64
 59   YEARS_BEGINEXPLUATATION_MODE  157504 non-null  float64
 60   YEARS_BUILD_MODE              103023 non-null  float64
 61   COMMONAREA_MODE               92646 non-null   float64
 62   ELEVATORS_MODE                143620 non-null  float64
 63   ENTRANCES_MODE                152683 non-null  float64
 64   FLOORSMAX_MODE                154491 non-null  float64
 65   FLOORSMIN_MODE                98869 non-null   float64
 66   LANDAREA_MODE                 124921 non-null  float64
 67   LIVINGAPARTMENTS_MODE         97312 non-null   float64
 68   LIVINGAREA_MODE               153161 non-null  float64
 69   NONLIVINGAPARTMENTS_MODE      93997 non-null   float64
 70   NONLIVINGAREA_MODE            137829 non-null  float64
 71   APARTMENTS_MEDI               151450 non-null  float64
 72   BASEMENTAREA_MEDI             127568 non-null  float64
 73   YEARS_BEGINEXPLUATATION_MEDI  157504 non-null  float64
 74   YEARS_BUILD_MEDI              103023 non-null  float64
 75   COMMONAREA_MEDI               92646 non-null   float64
 76   ELEVATORS_MEDI                143620 non-null  float64
 77   ENTRANCES_MEDI                152683 non-null  float64
 78   FLOORSMAX_MEDI                154491 non-null  float64
 79   FLOORSMIN_MEDI                98869 non-null   float64
 80   LANDAREA_MEDI                 124921 non-null  float64
 81   LIVINGAPARTMENTS_MEDI         97312 non-null   float64
 82   LIVINGAREA_MEDI               153161 non-null  float64
 83   NONLIVINGAPARTMENTS_MEDI      93997 non-null   float64
 84   NONLIVINGAREA_MEDI            137829 non-null  float64
 85   FONDKAPREMONT_MODE            307511 non-null  object
 86   HOUSETYPE_MODE                307511 non-null  object
 87   TOTALAREA_MODE                159080 non-null  float64
 88   WALLSMATERIAL_MODE            307511 non-null  object
 89   EMERGENCYSTATE_MODE           307511 non-null  object
 90   OBS_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 91   DEF_30_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 92   OBS_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 93   DEF_60_CNT_SOCIAL_CIRCLE      306490 non-null  float64
 94   DAYS_LAST_PHONE_CHANGE        307510 non-null  float64
 95   FLAG_DOCUMENT_2               307511 non-null  int64
 96   FLAG_DOCUMENT_3               307511 non-null  int64
 97   FLAG_DOCUMENT_4               307511 non-null  int64
 98   FLAG_DOCUMENT_5               307511 non-null  int64
 99   FLAG_DOCUMENT_6               307511 non-null  int64
 100  FLAG_DOCUMENT_7               307511 non-null  int64
 101  FLAG_DOCUMENT_8               307511 non-null  int64
 102  FLAG_DOCUMENT_9               307511 non-null  int64
 103  FLAG_DOCUMENT_10              307511 non-null  int64
 104  FLAG_DOCUMENT_11              307511 non-null  int64
 105  FLAG_DOCUMENT_12              307511 non-null  int64
 106  FLAG_DOCUMENT_13              307511 non-null  int64
 107  FLAG_DOCUMENT_14              307511 non-null  int64
 108  FLAG_DOCUMENT_15              307511 non-null  int64
 109  FLAG_DOCUMENT_16              307511 non-null  int64
 110  FLAG_DOCUMENT_17              307511 non-null  int64
 111  FLAG_DOCUMENT_18              307511 non-null  int64
 112  FLAG_DOCUMENT_19              307511 non-null  int64
 113  FLAG_DOCUMENT_20              307511 non-null  int64
 114  FLAG_DOCUMENT_21              307511 non-null  int64
 115  AMT_REQ_CREDIT_BUREAU_HOUR    265992 non-null  float64
 116  AMT_REQ_CREDIT_BUREAU_DAY     265992 non-null  float64
 117  AMT_REQ_CREDIT_BUREAU_WEEK    265992 non-null  float64
 118  AMT_REQ_CREDIT_BUREAU_MON     265992 non-null  float64
 119  AMT_REQ_CREDIT_BUREAU_QRT     265992 non-null  float64
 120  AMT_REQ_CREDIT_BUREAU_YEAR    265992 non-null  float64
dtypes: float64(65), int64(40), object(16)
memory usage: 286.2+ MB

In [8]:
raw_application_train_df.head(30)

,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
SK_ID_CURR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,351000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.018801,-9461,-637,-3648.0,-2120,NaN,1,1,0,1,1,0,Laborers,1.0,2,2,WEDNESDAY,10,0,0,0,0,0,0,Business Entity Type 3,0.083037,0.262949,0.139376,0.0247,0.0369,0.9722,0.6192,0.0143,0.00,0.0690,0.0833,0.1250,0.0369,0.0202,0.0190,0.0000,0.0000,0.0252,0.0383,0.9722,0.6341,0.0144,0.0000,0.0690,0.0833,0.1250,0.0377,0.0220,0.0198,0.0000,0.0000,0.0250,0.0369,0.9722,0.6243,0.0144,0.00,0.0690,0.0833,0.1250,0.0375,0.0205,0.0193,0.0000,0.0000,reg oper account,block of flats,0.0149,"Stone, brick",No,2.0,2.0,2.0,2.0,-1134.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,1129500.0,Family,State servant,Higher education,Married,House / apartment,0.003541,-16765,-1188,-1186.0,-291,NaN,1,1,0,1,1,0,Core staff,2.0,1,1,MONDAY,11,0,0,0,0,0,0,School,0.311267,0.622246,NaN,0.0959,0.0529,0.9851,0.7960,0.0605,0.08,0.0345,0.2917,0.3333,0.0130,0.0773,0.0549,0.0039,0.0098,0.0924,0.0538,0.9851,0.8040,0.0497,0.0806,0.0345,0.2917,0.3333,0.0128,0.0790,0.0554,0.0000,0.0000,0.0968,0.0529,0.9851,0.7987,0.0608,0.08,0.0345,0.2917,0.3333,0.0132,0.0787,0.0558,0.0039,0.0100,reg oper account,block of flats,0.0714,Block,No,1.0,0.0,1.0,0.0,-828.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,135000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.010032,-19046,-225,-4260.0,-2531,26.0,1,1,1,1,1,0,Laborers,1.0,2,2,MONDAY,9,0,0,0,0,0,0,Government,NaN,0.555912,0.729567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-815.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,297000.0,Unaccompanied,Working,Secondary / secondary special,Civil marriage,House / apartment,0.008019,-19005,-3039,-9833.0,-2437,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,17,0,0,0,0,0,0,Business Entity Type 3,NaN,0.650442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,2.0,0.0,2.0,0.0,-617.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,513000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.028663,-19932,-3038,-4311.0,-3458,NaN,1,1,0,1,0,0,Core staff,1.0,2,2,THURSDAY,11,0,0,0,0,1,1,Religion,NaN,0.322738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-1106.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,454500.0,"Spouse, partner",State servant,Secondary / secondary special,Married,House / apartment,0.035792,-16941,-1588,-4970.0,-477,NaN,1,1,1,1,1,0,Laborers,2.0,2,2,WEDNESDAY,16,0,0,0,0,0,0,Other,NaN,0.354225,0.621226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-2536.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,1395000.0,Unaccompanied,Commercial associate,Higher education,Married,House / apartment,0.035792,-13778,-3130,-1213.0,-619,17.0,1,1,0,1,1,0,Accountants,3.0,2,2,SUNDAY,16,0,0,0,0,0,0,Business Entity Type 3,0.774761,0.724000,0.492060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,1.0,0.0,1.0,0.0,-1562.0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,1530000.0,Unaccompanied,State servant,Higher education,Married,House / apartment,0.003122,-18850,-449,-4597.0,-2379,8.0,1,1,1,1,0,0,Managers,2.0,3,3,MONDAY,16,0,0,0,0,1,1,Other,NaN,0.714279,0.540654,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,2.0,0.0,2.0,0.0,-1070.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,405000.0,Unaccompanied,Working,Secondary / secondary special,Single / not married,House / apartment,0.019689,-14469,-2019,-14437.0,-3992,NaN,1,1,0,1,0,0,Laborers,1.0,2,2,THURSDAY,8,0,0,0,0,0,0,Electricity,NaN,0.746644,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,2.0,0.0,2.0,0.0,-1673.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,652500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.022800,-10197,-679,-4427.0,-738,NaN,1,1,0,1,0,0,Core staff,3.0,2,2,SATURDAY,15,0,0,0,0,0,0,Medicine,0.319760,0.651862,0.363945,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-844.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,135000.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.015221,-20417,365243,-5246.0,-2512,NaN,1,0,0,1,1,0,,2.0,2,2,FRIDAY,7,0,0,0,0,0,0,XNA,0.722044,0.555183,0.652897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-2396.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,67500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.031329,-13439,-2717,-311.0,-3227,NaN,1,1,1,1,1,0,Laborers,2.0,2,2,FRIDAY,10,0,0,0,0,0,0,Business Entity Type 2,0.464831,0.715042,0.176653,0.0825,NaN,0.9811,NaN,NaN,0.00,0.2069,0.1667,NaN,0.0135,NaN,0.0778,NaN,0.0000,0.0840,NaN,0.9811,NaN,NaN,0.0000,0.2069,0.1667,NaN,0.0138,NaN,0.0810,NaN,0.0000,0.0833,NaN,0.9811,NaN,NaN,0.00,0.2069,0.1667,NaN,0.0137,NaN,0.0792,NaN,0.0000,reg oper account,block of flats,0.0612,,No,0.0,0.0,0.0,0.0,-2370.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,697500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.016612,-14086,-3028,-643.0,-4911,23.0,1,1,0,1,0,0,Drivers,3.0,2,2,THURSDAY,13,0,0,0,0,0,0,Self-employed,NaN,0.566907,0.770087,0.1474,0.0973,0.9806,0.7348,0.0582,0.16,0.1379,0.3333,0.3750,0.0931,0.1202,0.1397,0.0000,0.0000,0.1502,0.1010,0.9806,0.7452,0.0587,0.1611,0.1379,0.3333,0.3750,0.0952,0.1313,0.1456,0.0000,0.0000,0.1489,0.0973,0.9806,0.7383,0.0585,0.16,0.1379,0.3333,0.3750,0.0947,0.1223,0.1422,0.0000,0.0000,reg oper account,block of flats,0.1417,Panel,No,0.0,0.0,0.0,0.0,-4.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,679500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010006,-14583,-203,-615.0,-2056,NaN,1,1,0,1,0,0,Laborers,2.0,2,1,MONDAY,9,0,0,0,0,0,0,Transport: type 2,0.721940,0.642656,NaN,0.3495,0.1335,0.9985,0.9796,0.1143,0.40,0.1724,0.6667,0.7083,0.1758,0.2849,0.3774,0.0193,0.1001,0.3561,0.1386,0.9985,0.9804,0.1153,0.4028,0.1724,0.6667,0.7083,0.1798,0.3113,0.3932,0.0195,0.1060,0.3529,0.1335,0.9985,0.9799,0.1150,0.40,0.1724,0.6667,0.7083,0.1789,0.2899,0.3842,0.0194,0.1022,reg oper account,block of flats,0.3811,Panel,No,0.0,0.0,0.0,0.0,-188.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,247500.0,Family,Working,Secondary / secondary special,Single / not married,Rented apartment,0.020713,-8728,-1157,-3494.0,-1368,17.0,1,1,0,1,0,0,Laborers,1.0,3,3,SATURDAY,6,0,0,0,1,1,0,Business Entity Type 2,0.115634,0.346634,0.678568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-925.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,387000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.018634,-12931,-1317,-6392.0,-3866,NaN,1,1,0,1,0,0,Drivers,2.0,2,2,THURSDAY,12,0,0,0,1,1,0,Government,NaN,0.236378,0.062103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-3.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,270000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010966,-9776,-191,-4143.0,-2427,NaN,1,1,0,1,0,0,Laborers,3.0,2,2,MONDAY,10,0,0,0,1,1,0,Construction,NaN,0.683513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,4.0,0.0,4.0,0.0,-2811.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,157500.0,Other_A,Working,Secondary / secondary special,Widow,House / apartment,0.046220,-17718,-7804,-8751.0,-1259,NaN,1,1,0,1,1,0,Laborers,1.0,1,1,FRIDAY,13,0,0,0,0,0,0,Housing,NaN,0.706428,0.556727,0.0278,0.0617,0.9881,0.8368,0.0018,0.00,0.1034,0.0833,0.1250,0.0279,0.0227,0.0290,0.0000,0.0000,0.0284,0.0640,0.9881,0.8432,0.0018,0.0000,0.1034,0.0833,0.1250,0.0286,0.0248,0.0302,0.0000,0.0000,0.0281,0.0617,0.9881,0.8390,0.0018,0.00,0.1034,0.0833,0.1250,0.0284,0.0231,0.0295,0.0000,0.0000,reg oper account,block of flats,0.0238,"Stone, brick",No,8.0,0.0,8.0,0.0,-239.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,454500.0,Unaccompanied,State servant,Higher education,Single / not married,House / apartment,0.015221,-11348,-2038,-1021.0,-3964,NaN,1,1,1,1,1,0,Core staff,2.0,2,2,MONDAY,12,0,0,0,0,0,0,Kindergarten,NaN,0.586617,0.477649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-1850.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,427500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.015221,-18252,-4286,-298.0,-1800,7.0,1,1,0,1,0,0,Laborers,2.0,2,2,FRIDAY,13,0,0,0,0,0,0,Self-employed,0.565655,0.113375,NaN,0.0722,0.0801,0.9781,0.7008,NaN,0.00,0.1379,0.1667,0.0417,0.0534,0.0588,0.0619,0.0000,0.0000,0.0735,0.0831,0.9782,0.7125,NaN,0.0000,0.1379,0.1667,0.0417,0.0546,0.0643,0.0645,0.0000,0.0000,0.0729,0.0801,0.9781,0.7048,NaN,0.00,0.1379,0.1667,0.0417,0.0543,0.0599,0.0630,0.0000,0.0000,reg oper account,block of flats,0.0530,"Stone, brick",No,0.0,0.0,0.0,0.0,-296.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,927000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.025164,-14815,-1652,-2299.0,-2299,14.0,1,1,0,1,0,0,Sales staff,3.0,2,2,MONDAY,9,0,0,0,0,0,0,Trade: type 7,0.437709,0.233767,0.542445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,450000.0,Unaccompanied,Working,Secondary / secondary special,Married,Rented apartment,0.020713,-11146,-4306,-114.0,-2518,NaN,1,1,0,1,0,0,Sales staff,3.0,3,2,THURSDAY,6,0,0,0,0,0,0,Self-employed,NaN,0.457143,0.358951,0.0907,0.0795,0.9786,0.7076,0.0120,0.00,0.2069,0.1667,0.2083,0.0898,0.0723,0.0873,0.0077,0.0044,0.0924,0.0825,0.9786,0.7190,0.0121,0.0000,0.2069,0.1667,0.2083,0.0918,0.0790,0.0910,0.0078,0.0047,0.0916,0.0795,0.9786,0.7115,0.0120,0.00,0.2069,0.1667,0.2083,0.0913,0.0735,0.0889,0.0078,0.0045,reg oper account,block of flats,0.0696,Panel,No,0.0,0.0,0.0,0.0,-468.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,225000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,House / apartment,0.006296,-24827,365243,-9012.0,-3684,NaN,1,0,0,1,1,0,,2.0,3,3,FRIDAY,12,0,0,0,0,0,0,XNA,NaN,0.624305,0.669057,0.1443,0.0848,0.9876,0.8300,0.1064,0.14,0.1207,0.3750,0.4167,0.2371,0.1173,0.1484,0.0019,0.0007,0.1261,0.0754,0.9876,0.8367,0.0000,0.1208,0.1034,0.3750,0.4167,0.2425,0.1102,0.0923,0.0000,0.0000,0.1457,0.0848,0.9876,0.8323,0.1071,0.14,0.1207,0.3750,0.4167,0.2412,0.1193,0.1510,0.0019,0.0007,org spec account,block of flats,0.1640,Mixed,No,0.0,0.0,0.0,0.0,-795.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,247500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.026392,-11286,-746,-108.0,-3729,7.0,1,1,0,1,0,0,Drivers,4.0,2,2,THURSDAY,14,0,0,0,0,1,1,Business Entity Type 3,NaN,0.786179,0.565608,0.1433,0.1455,0.9861,0.8096,0.0212,0.00,0.3103,0.1667,0.2083,0.0861,0.1168,0.1217,0.0000,0.0043,0.1460,0.1509,0.9861,0.8171,0.0214,0.0000,0.3103,0.1667,0.2083,0.0881,0.1276,0.1268,0.0000,0.0045,0.1447,0.1455,0.9861,0.8121,0.0214,0.00,0.3103,0.1667,0.2083,0.0876,0.1189,0.1239,0.0000,0.0044,reg oper account,block of flats,0.0967,Panel,No,1.0,1.0,1.0,0.0,-4.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,225000.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.028663,-19334,-3494,-2419.0,-2893,NaN,1,1,0,1,1,0,Cleaning staff,2.0,2,2,SATURDAY,8,0,0,0,0,0,0,Business Entity Type 3,0.561948,0.651406,0.461482,0.0722,0.0147,0.9781,0.7008,0.0010,0.00,0.1379,0.1667,0.0417,0.0498,0.0588,0.0670,0.0000,0.0000,0.0735,0.0153,0.9782,0.7125,0.0010,0.0000,0.1379,0.1667,0.0417,0.0509,0.0643,0.0698,0.0000,0.0000,0.0729,0.0147,0.9781,0.7048,0.0010,0.00,0.1379,0.1667,0.0417,0.0506,0.0599,0.0682,0.0000,0.0000,reg oper account,block of flats,0.0533,"Stone, brick",No,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,702000.0,Unaccompanied,Working,Secondary / secondary special,Widow,House / apartment,0.018029,-18724,-2628,-6573.0,-1827,NaN,1,1,0,1,0,0,Cooking staff,1.0,3,2,MONDAY,9,0,0,0,0,0,0,Business Entity Type 3,NaN,0.548477,0.190706,0.0165,0.0089,0.9732,NaN,NaN,0.00,0.0690,0.0417,NaN,0.0265,NaN,0.0094,NaN,0.0000,0.0168,0.0092,0.9732,NaN,NaN,0.0000,0.0690,0.0417,NaN,0.0271,NaN,0.0083,NaN,0.0000,0.0167,0.0089,0.9732,NaN,NaN,0.00,0.0690,0.0417,NaN,0.0270,NaN,0.0096,NaN,0.0000,,block of flats,0.0085,Wooden,Yes,10.0,1.0,10.0,0.0,-161.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,270000.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.019101,-15948,-1234,-5782.0,-3153,NaN,1,1,0,1,0,0,Laborers,3.0,2,2,SATURDAY,10,0,0,0,0,1,1,Industry: type 11,NaN,0.541124,0.659406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,2.0,0.0,2.0,0.0,-2.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,675000.0,Unaccompanied,State servant,Higher education,Single / not married,House / apartment,0.046220,-9994,-1796,-4668.0,-2661,1.0,1,1,0,1,0,1,,1.0,1,1,WEDNESDAY,11,0,1,1,0,0,0,Military,0.600396,0.685011,0.524496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,NaN,,,0.0,0.0,0.0,0.0,-849.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0

### 2.1. Classificar os tipos de dados

In [9]:
unique_id_variables = ["SK_ID_CURR"]

target_variables = ["TARGET"]

cat_variables = [
    col
    for col in raw_application_train_df.columns.to_list()
    if any(substring in col for substring in ["FLAG", "NAME", "RATING", "CODE"])
] + [
    "WEEKDAY_APPR_PROCESS_START",
    "FONDKAPREMONT_MODE",
    "HOUSETYPE_MODE",
    "NAME_TYPE_SUITE",
    "WALLSMATERIAL_MODE",
    "EMERGENCYSTATE_MODE",
]
cat_variables = list(
    set(cat_variables).difference(
        set(
            col
            for col in raw_application_train_df.columns.to_list()
            if any(substring in col for substring in ["FLAG_DOCUMENT"])
        )
    )
)

int_variables = [
    col
    for col in raw_application_train_df.columns.to_list()
    if any(substring in col for substring in ["AMT_REQ_CREDIT"])
]

float_variables = [
    col
    for col in raw_application_train_df.columns.to_list()
    if any(substring in col for substring in ["AMT_", "EXT_", "_AVG", "_MODE", "_MEDI"])
] + [
    "REGION_POPULATION_RELATIVE",
]
float_variables = list(
    set(float_variables).difference(set(cat_variables)).difference(set(int_variables))
)

time_interval_variables = [
    col
    for col in raw_application_train_df.columns.to_list()
    if any(
        substring in col for substring in ["YEARS", "MONTHS", "DAYS", "HOURS", "MINS"]
    )
]
time_interval_variables = list(
    set(time_interval_variables).difference(set(float_variables))
)

datetime_variables = [
    col
    for col in raw_application_train_df.columns.to_list()
    if any(substring in col for substring in ["YEAR", "MONTH", "DAY", "HOUR"])
]
datetime_variables = list(
    set(datetime_variables)
    .difference(set(cat_variables))
    .difference(set(int_variables))
    .difference(set(float_variables))
    .difference(set(time_interval_variables))
)


text_variables = []

print(
    f"""
Unique ID Variables: {unique_id_variables}

Target Variables: {target_variables}

Categorial Variables: {cat_variables}

Integer Variables: {int_variables}

Float Variables: {float_variables}

Time Interval Variables: {time_interval_variables}

Datetime Variables: {datetime_variables}

Text Variables: {text_variables}
"""
)

Unique ID Variables: ['SK_ID_CURR']

Target Variables: ['TARGET']

Categorial Variables: ['FONDKAPREMONT_MODE', 'FLAG_EMAIL', 'WEEKDAY_APPR_PROCESS_START', 'CODE_GENDER', 'EMERGENCYSTATE_MODE', 'FLAG_CONT_MOBILE', 'NAME_FAMILY_STATUS', 'REGION_RATING_CLIENT_W_CITY', 'HOUSETYPE_MODE', 'FLAG_WORK_PHONE', 'NAME_INCOME_TYPE', 'FLAG_OWN_CAR', 'NAME_TYPE_SUITE', 'FLAG_MOBIL', 'FLAG_PHONE', 'FLAG_OWN_REALTY', 'NAME_CONTRACT_TYPE', 'WALLSMATERIAL_MODE', 'NAME_HOUSING_TYPE', 'REGION_RATING_CLIENT', 'NAME_EDUCATION_TYPE', 'FLAG_EMP_PHONE']

Integer Variables: ['AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR']

Float Variables: ['COMMONAREA_AVG', 'BASEMENTAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'EXT_SOURCE_3', 'ELEVATORS_AVG', 'YEARS_BEGINEXPLUATATION_MODE', 'COMMONAREA_MODE', 'FLOORSMAX_MEDI', 'BASEMENTAREA_AVG', 'AMT_INCOME_TOTAL', 'LANDAREA_AVG', 'EXT_SOURCE_1', 'REGION_POPULATION_RELATIVE', 'BASEMENTAREA_MEDI', 'APARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'YEARS_BUILD_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_MEDI', 'LIVINGAPARTMENTS_MODE', 'FLOORSMIN_AVG', 'EXT_SOURCE_2', 'FLOORSMAX_AVG', 'AMT_CREDIT', 'LIVINGAREA_MEDI', 'LIVINGAPARTMENTS_AVG', 'ENTRANCES_AVG', 'LANDAREA_MODE', 'ELEVATORS_MEDI', 'YEARS_BUILD_MODE', 'ENTRANCES_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'COMMONAREA_MEDI', 'AMT_ANNUITY', 'FLOORSMIN_MODE', 'FLOORSMIN_MEDI', 'ELEVATORS_MODE', 'YEARS_BEGINEXPLUATATION_AVG', 'FLOORSMAX_MODE', 'APARTMENTS_AVG', 'LANDAREA_MEDI', 'LIVINGAREA_MODE', 'LIVINGAREA_AVG', 'YEARS_BUILD_MEDI', 'ENTRANCES_MODE', 'TOTALAREA_MODE', 'APARTMENTS_MEDI', 'LIVINGAPARTMENTS_MEDI', 'AMT_GOODS_PRICE', 'NONLIVINGAREA_MEDI']

Time Interval Variables: ['DAYS_BIRTH', 'DAYS_ID_PUBLISH', 'DAYS_EMPLOYED', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION']

Datetime Variables: ['HOUR_APPR_PROCESS_START']

Text Variables: []

In [10]:
cat_ordinal_vars = [
    "REGION_RATING_CLIENT",
    "REGION_RATING_CLIENT_W_CITY"
]

cat_nominal_vars = list(
    set(cat_variables)
    .difference(set(cat_ordinal_vars))
)

num_continuous_vars = float_variables.copy()

num_discrete_vars = int_variables + time_interval_variables



print(
    f"""
Categorial Ordinal Variables: {cat_ordinal_vars}

Categorial Nominal Variables: {cat_nominal_vars}

Numeric Continuous Variables: {num_continuous_vars}

Numeric Discrete Variables: {num_discrete_vars}

Datetime Variables: {datetime_variables}
"""
)

Categorial Ordinal Variables: ['REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY']

Categorial Nominal Variables: ['FONDKAPREMONT_MODE', 'FLAG_EMAIL', 'WEEKDAY_APPR_PROCESS_START', 'CODE_GENDER', 'NAME_TYPE_SUITE', 'FLAG_MOBIL', 'NAME_EDUCATION_TYPE', 'FLAG_PHONE', 'EMERGENCYSTATE_MODE', 'FLAG_OWN_REALTY', 'NAME_CONTRACT_TYPE', 'FLAG_CONT_MOBILE', 'WALLSMATERIAL_MODE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'HOUSETYPE_MODE', 'FLAG_WORK_PHONE', 'NAME_INCOME_TYPE', 'FLAG_EMP_PHONE', 'FLAG_OWN_CAR']

Numeric Continuous Variables: ['COMMONAREA_AVG', 'BASEMENTAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'EXT_SOURCE_3', 'ELEVATORS_AVG', 'YEARS_BEGINEXPLUATATION_MODE', 'COMMONAREA_MODE', 'FLOORSMAX_MEDI', 'BASEMENTAREA_AVG', 'AMT_INCOME_TOTAL', 'LANDAREA_AVG', 'EXT_SOURCE_1', 'REGION_POPULATION_RELATIVE', 'BASEMENTAREA_MEDI', 'APARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'YEARS_BUILD_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_MEDI', 'LIVINGAPARTMENTS_MODE', 'FLOORSMIN_AVG', 'EXT_SOURCE_2', 'FLOORSMAX_AVG', 'AMT_CREDIT', 'LIVINGAREA_MEDI', 'LIVINGAPARTMENTS_AVG', 'ENTRANCES_AVG', 'LANDAREA_MODE', 'ELEVATORS_MEDI', 'YEARS_BUILD_MODE', 'ENTRANCES_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'COMMONAREA_MEDI', 'AMT_ANNUITY', 'FLOORSMIN_MODE', 'FLOORSMIN_MEDI', 'ELEVATORS_MODE', 'YEARS_BEGINEXPLUATATION_AVG', 'FLOORSMAX_MODE', 'APARTMENTS_AVG', 'LANDAREA_MEDI', 'LIVINGAREA_MODE', 'LIVINGAREA_AVG', 'YEARS_BUILD_MEDI', 'ENTRANCES_MODE', 'TOTALAREA_MODE', 'APARTMENTS_MEDI', 'LIVINGAPARTMENTS_MEDI', 'AMT_GOODS_PRICE', 'NONLIVINGAREA_MEDI']

Numeric Discrete Variables: ['AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'DAYS_BIRTH', 'DAYS_ID_PUBLISH', 'DAYS_EMPLOYED', 'DAYS_LAST_PHONE_CHANGE', 'DAYS_REGISTRATION']

Datetime Variables: ['HOUR_APPR_PROCESS_START']

In [11]:
project_parameters_file = PurePath("../../conf/base/parameters.yml")

with open(project_parameters_file, "r") as file:
    project_parameters = yaml.safe_load(file)

project_parameters

{'dataset_variables_types': {'application_test': {'categorical_nominal': ['EMERGENCYSTATE_MODE',
    'FLAG_OWN_REALTY',
    'NAME_EDUCATION_TYPE',
    'WEEKDAY_APPR_PROCESS_START',
    'FLAG_MOBIL',
    'FLAG_EMP_PHONE',
    'FONDKAPREMONT_MODE',
    'FLAG_OWN_CAR',
    'WALLSMATERIAL_MODE',
    'NAME_TYPE_SUITE',
    'FLAG_PHONE',
    'FLAG_CONT_MOBILE',
    'NAME_CONTRACT_TYPE',
    'CODE_GENDER',
    'HOUSETYPE_MODE',
    'NAME_INCOME_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'FLAG_WORK_PHONE',
    'FLAG_EMAIL'],
   'categorical_ordinal': ['REGION_RATING_CLIENT',
    'REGION_RATING_CLIENT_W_CITY'],
   'datetime': ['HOUR_APPR_PROCESS_START'],
   'numerical_continuous': ['COMMONAREA_AVG',
    'LANDAREA_MODE',
    'YEARS_BEGINEXPLUATATION_MEDI',
    'TOTALAREA_MODE',
    'LANDAREA_AVG',
    'BASEMENTAREA_MEDI',
    'NONLIVINGAREA_MEDI',
    'LANDAREA_MEDI',
    'FLOORSMAX_AVG',
    'ENTRANCES_MODE',
    'LIVINGAPARTMENTS_MODE',
    'YEARS_BEGINEXPLUATATION_AVG',
    'BASEMENTAREA_MODE',
    'FLOORSMIN_MODE',
    'YEARS_BUILD_MEDI',
    'FLOORSMAX_MEDI',
    'EXT_SOURCE_2',
    'APARTMENTS_AVG',
    'NONLIVINGAREA_MODE',
    'AMT_INCOME_TOTAL',
    'ELEVATORS_MEDI',
    'NONLIVINGAREA_AVG',
    'NONLIVINGAPARTMENTS_MODE',
    'AMT_GOODS_PRICE',
    'NONLIVINGAPARTMENTS_AVG',
    'NONLIVINGAPARTMENTS_MEDI',
    'LIVINGAPARTMENTS_AVG',
    'EXT_SOURCE_1',
    'FLOORSMIN_AVG',
    'YEARS_BUILD_MODE',
    'BASEMENTAREA_AVG',
    'ENTRANCES_MEDI',
    'COMMONAREA_MEDI',
    'REGION_POPULATION_RELATIVE',
    'ELEVATORS_MODE',
    'FLOORSMIN_MEDI',
    'ELEVATORS_AVG',
    'COMMONAREA_MODE',
    'ENTRANCES_AVG',
    'YEARS_BUILD_AVG',
    'AMT_CREDIT',
    'FLOORSMAX_MODE',
    'AMT_ANNUITY',
    'EXT_SOURCE_3',
    'LIVINGAPARTMENTS_MEDI',
    'APARTMENTS_MODE',
    'LIVINGAREA_MEDI',
    'YEARS_BEGINEXPLUATATION_MODE',
    'LIVINGAREA_MODE',
    'LIVINGAREA_AVG',
    'APARTMENTS_MEDI'],
   'numerical_discrete': ['AMT_REQ_CREDIT_BUREAU_HOUR',
    'AMT_REQ_CREDIT_BUREAU_DAY',
    'AMT_REQ_CREDIT_BUREAU_WEEK',
    'AMT_REQ_CREDIT_BUREAU_MON',
    'AMT_REQ_CREDIT_BUREAU_QRT',
    'AMT_REQ_CREDIT_BUREAU_YEAR',
    'DAYS_EMPLOYED',
    'DAYS_REGISTRATION',
    'DAYS_BIRTH',
    'DAYS_LAST_PHONE_CHANGE',
    'DAYS_ID_PUBLISH']},
  'application_train': {'categorical_nominal': ['EMERGENCYSTATE_MODE',
    'FLAG_OWN_REALTY',
    'NAME_EDUCATION_TYPE',
    'WEEKDAY_APPR_PROCESS_START',
    'FLAG_MOBIL',
    'FLAG_EMP_PHONE',
    'FONDKAPREMONT_MODE',
    'FLAG_OWN_CAR',
    'WALLSMATERIAL_MODE',
    'NAME_TYPE_SUITE',
    'FLAG_PHONE',
    'FLAG_CONT_MOBILE',
    'NAME_CONTRACT_TYPE',
    'CODE_GENDER',
    'HOUSETYPE_MODE',
    'NAME_INCOME_TYPE',
    'NAME_FAMILY_STATUS',
    'NAME_HOUSING_TYPE',
    'FLAG_WORK_PHONE',
    'FLAG_EMAIL'],
   'categorical_ordinal': ['REGION_RATING_CLIENT',
    'REGION_RATING_CLIENT_W_CITY'],
   'datetime': ['HOUR_APPR_PROCESS_START'],
   'numerical_continuous': ['COMMONAREA_AVG',
    'LANDAREA_MODE',
    'YEARS_BEGINEXPLUATATION_MEDI',
    'TOTALAREA_MODE',
    'LANDAREA_AVG',
    'BASEMENTAREA_MEDI',
    'NONLIVINGAREA_MEDI',
    'LANDAREA_MEDI',
    'FLOORSMAX_AVG',
    'ENTRANCES_MODE',
    'LIVINGAPARTMENTS_MODE',
    'YEARS_BEGINEXPLUATATION_AVG',
    'BASEMENTAREA_MODE',
    'FLOORSMIN_MODE',
    'YEARS_BUILD_MEDI',
    'FLOORSMAX_MEDI',
    'EXT_SOURCE_2',
    'APARTMENTS_AVG',
    'NONLIVINGAREA_MODE',
    'AMT_INCOME_TOTAL',
    'ELEVATORS_MEDI',
    'NONLIVINGAREA_AVG',
    'NONLIVINGAPARTMENTS_MODE',
    'AMT_GOODS_PRICE',
    'NONLIVINGAPARTMENTS_AVG',
    'NONLIVINGAPARTMENTS_MEDI',
    'LIVINGAPARTMENTS_AVG',
    'EXT_SOURCE_1',
    'FLOORSMIN_AVG',
    'YEARS_BUILD_MODE',
    'BASEMENTAREA_AVG',
    'ENTRANCES_MEDI',
    'COMMONAREA_MEDI',
    'REGION_POPULATION_RELATIVE',
    'ELEVATORS_MODE',
    'FLOORSMIN_MEDI',
    'ELEVATORS_AVG',
    'COMMONAREA_MODE',
    'ENTRANCES_AVG',
    'YEARS_BUILD_AVG',
    'AMT_CREDIT',
    'FLOORSMAX_MODE',
    'AMT_ANNUITY',
    'EXT_SOURCE_3',
    'LIVINGAPARTMENTS_MEDI',
    'APARTMENTS_MODE',
    'LIVINGAREA_MEDI',
    'YEARS_BEGINEXPLUATATION_MODE',
    'LIVINGAREA_MODE',
    'LIVINGAREA_AVG',
    'APARTMENTS_MEDI'],
   'numerical_discrete': ['AMT_REQ_CREDIT_BUREAU_HOUR',
    'AMT_REQ_CREDIT_BUREAU_DAY',
    'AMT_REQ_CREDIT_BUREAU_WEEK',
    'AMT_REQ_CREDIT_BUREAU_MON',
    'AMT_REQ_CREDIT_BUREAU_QRT',
    'AMT_REQ_CREDIT_BUREAU_YEAR',
    'DAYS_EMPLOYED',
    'DAYS_REGISTRATION',
    'DAYS_BIRTH',
    'DAYS_LAST_PHONE_CHANGE',
    'DAYS_ID_PUBLISH']}},
 'target': ['TARGET']}

In [12]:
project_parameters["dataset_variables_types"] = {
    "application_train": {
        "categorical_ordinal": cat_ordinal_vars,
        "categorical_nominal": cat_nominal_vars,
        "numerical_continuous": num_continuous_vars,
        "numerical_discrete": num_discrete_vars,
        "datetime": datetime_variables
    },
    "application_test": {
        "categorical_ordinal": cat_ordinal_vars,
        "categorical_nominal": cat_nominal_vars,
        "numerical_continuous": num_continuous_vars,
        "numerical_discrete": num_discrete_vars,
        "datetime": datetime_variables
    }
}

project_parameters["target"] = target_variables

In [13]:
with open(project_parameters_file, "w") as file:
    yaml.safe_dump(project_parameters, file)